import type { Metadata } from "next";
import { Sulphur_Point } from "next/font/google";
import "./globals.css";

const sulphur_point = Sulphur_Point({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sulphur_point.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
